# Generated by Django 6.0.1 on 2026-01-20 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(help_text='Nomor KTP', max_length=16, unique=True)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=15)),
                ('tanggal_gabung', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rekening', models.CharField(editable=False, max_length=10, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jenis', models.CharField(choices=[('SILVER', 'Galaxy Silver'), ('GOLD', 'Galaxy Gold'), ('PLATINUM', 'Galaxy Platinum')], default='SILVER', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekening', to='banking.nasabah')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('SETOR', 'Setor Tunai'), ('TARIK', 'Tarik Tunai'), ('TRANSFER', 'Transfer Sesama')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.rekening')),
                ('teller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
