# Generated by Django 6.0.1 on 2026-01-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rekening",
            name="tipe",
            field=models.CharField(
                choices=[
                    ("PRIBADI", "Rekening Pribadi"),
                    ("BISNIS", "Rekening Bisnis"),
                ],
                default="PRIBADI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rekening",
            name="saldo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaksi",
            name="jenis",
            field=models.CharField(
                choices=[
                    ("SETOR", "Setor Tunai"),
                    ("TARIK", "Tarik Tunai"),
                    ("TRANSFER", "Transfer Sesama"),
                    ("BAYAR", "Pembayaran Tagihan"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaksi",
            name="nominal",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name="Tagihan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomor_tagihan",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "jenis_layanan",
                    models.CharField(
                        choices=[
                            ("LISTRIK", "Listrik / PLN"),
                            ("INTERNET", "Internet / Wifi"),
                            ("PAJAK", "Pajak"),
                            ("BELANJA", "Belanja / E-Commerce"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=15)),
                ("deskripsi", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("BELUM", "Belum Dibayar"), ("LUNAS", "Lunas")],
                        default="BELUM",
                        max_length=10,
                    ),
                ),
                ("waktu_dibuat", models.DateTimeField(auto_now_add=True)),
                ("waktu_dibayar", models.DateTimeField(blank=True, null=True)),
                (
                    "pembayar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tagihan_dibayar",
                        to="banking.rekening",
                    ),
                ),
                (
                    "pembuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagihan_dibuat",
                        to="banking.rekening",
                    ),
                ),
            ],
        ),
    ]
